### ISSUE TITLE
Initial use of VPP API via Go

### ISSUE THREAD

**Issue by edwarnicke** [godirect/hoststack#1]
As a first problem to get going,  crib off of https://github.com/edwarnicke/govpp/blob/main/_examples/showver/main.go

Which can be run in a docker container: https://github.com/edwarnicke/govpp/blob/main/_examples/showver/Dockerfile

To get your first experience of using the VPP API to connect to VPP.

Change to using ['show version verbose'](https://docs.fd.io/vpp/21.01/d3/dfb/clicmd_src_vpp_app_version_c.html#clicmd_show_version).

Note the information about the API you just called here: https://github.com/FDio/vpp/blob/master/src/vpp/api/vpe.api#L91

Push a PR showing your work.

**Comment by edwarnicke** [comment]
@harshgondaliya - start here.  If you accept the invite from Github to the repo, I can assign you in the normal way.

@florincoras - FYI :)

**Comment by harshgondaliya** [comment]
Hi @edwarnicke 

I just submitted a PR having updated showver app that shows verbose level version details.
Sorry for the delayed start. I think I had gone on the wrong path for this exercise. 
I was searching for a Golang binding that can directly give my verbose level details.

Then realized that I need to use `vpe.ShowVersion` API itself and print more fields of the `ShowVersionReply` struct.

However, with the parameters available in the `ShowVersionReply` struct, I don't think I can print `Compiled by:`, `Compile host:`, `Compiler:`, and `Current PID:` details. These are shown when using `show version verbose` command through CLI.

**Comment by edwarnicke** [comment]
@harshgondaliya A couple of things :)

1. I see you pushed the PR here: https://github.com/edwarnicke/govpp/pull/22
2. Could you push a PR for that code to godirect/hoststack?

**Comment by harshgondaliya** [comment]
@edwarnicke Just submitted a PR showing my work for this exercise.

**Comment by edwarnicke** [comment]
Close by https://github.com/godirect/hoststack/pull/3
