### ISSUE TITLE
Structuring Code

### ISSUE THREAD

**Issue by edwarnicke** [godirect/hoststack#14]
******* Note: this issue is as yet incomplete ************

So far, we've been layering things into main().  As we move forward, we need to structure things a bit more.

To begin with, lets define in namespace.go:

```go
type Namespace struct {
    vppconn api.Connection
    id string
    udsConn net.Conn
}

func NewNamespace(vppconn api.Connection, id string) *Namespace {
   return &Namespace{
        vppconn: vppconn,
        id: id,
    }
}

func (ns *Namespace) Dial() {
   // Put logic here similar to https://github.com/godirect/hoststack/blob/main/app-attach/main.go#L112-L120 and store the result in ns.udsConn
}

func (ns *Namespace) Attach() *Attachment {
  // 
  // Put logic here similar to https://github.com/godirect/hoststack/blob/1aad8f0fdaa47bc3c84c46ffd4109c182d186de3/app-attach/main.go#L121-L175
  // store the AppAttachReplyMsg in ns.appAttachReplyMsg
  // More a bit further on about what to do with the fds you got in this process
}
```

which of course requires defining in attachment.go:
```go 
type struct Attachment {
   ns *Namespace
   appAttachReplyMsg *AppAttachReplyMsg
   vppMqMemorySegment *MemorySegment
   workers []*Worker
}

func NewAttachment(ns *Namespace, udsConn net.Conn) *Attachment {
    attachment := &Attachment{
        ns:ns,
        appAttachReplyMsg: appAttachReplyMsg,
    }
    // Put logic here similar to https://github.com/godirect/hoststack/blob/1aad8f0fdaa47bc3c84c46ffd4109c182d186de3/app-attach/main.go#L121-L175
    // store the AppAttachReplyMsg in attachment.appAttachReplyMsg
    // Put logic here similar to https://github.com/godirect/hoststack/blob/main/app-attach/main.go#L176-L200
    // to extract the memfds.  Create a MemorySegment for each.
    // Precisely one of those MemorySegments should have MemorySegment.IsVppMqMemorySegment() == true.
    //  Store that one in attachment.vppMqMemorySegment
    //  Other MemorySegments for which MemorySegment.IsVppMqMemorySegment() == false
    //  store in attachment.workers
}
```

Create a new type to represent a memory segment.  I would recommend putting it in a file named memory_segment.go You probably want to start with something like:

```go
type MemorySegment struct {
    attachment *Attachment
    memfd *memf.Memfd
    mappedBytes []byte
}

func NewMemorySegment(attachment *Attachment, fd int) *MemorySegment {
       return &MemorySegment{
        attachment: attachment,
        memfd: memfd,  // extract from fd to memfd similar to the logic https://github.com/godirect/hoststack/blob/1aad8f0fdaa47bc3c84c46ffd4109c182d186de3/app-attach/main.go#L182-L185

        mappedBytes: // extract similar to the logic https://github.com/godirect/hoststack/blob/1aad8f0fdaa47bc3c84c46ffd4109c182d186de3/app-attach/main.go#L186-L189
    }
}
```

And in worker.go

```go
type Worker struct {
  memorySegment *MemorySegment
}

func NewWorker(memorySegment *MemorySegment) *Worker {
    return &Worker{memorySegment:memorySegment }
}
```

**Comment by florincoras** [comment]
Quick answers:
Q1: We get a segment handle only for `SESSION_FD_F_MEMFD_SEGMENT`. For `SESSION_FD_F_VPP_MQ_SEGMENT` we can just give it a constant name, vpp will never send an unmap message for it. And the eventfds, if any are present, are not mmaped. 
Q2: Not entirely sure what the question is, but 1) message queues in `VPP_MQ_SEGMENT` are discovered (unmarshaled) and some private structures need to be created and remembered (there's 1 mq per vpp thread, i.e., main and all workers) 2) in `MEMFD_SEGMENT` there's only one queue and we do something similar. This mq is the one that will receive messages from vpp.

**Comment by florincoras** [comment]
Looks good! Some quick comments:
- I’d make a separate structure for workers. They'll need to track a lot of things and each worker will map multiple fifo segments. 
- We'll also need to unmap segments. No preference for naming but we should choose a pair of prefixes and use it consistently (e.g., new/free or map/unmap or attach/detach)
- If we plan to make `Attachment` a global variable, not sure we'll want/need to track `AppAttachReplyMsg` in it.

**Comment by edwarnicke** [comment]
> I’d make a separate structure for workers. They'll need to track a lot of things and each worker will map multiple fifo segments.

Done.

**Comment by edwarnicke** [comment]
> We'll also need to unmap segments. No preference for naming but we should choose a pair of prefixes and use it consistently (e.g., new/free or map/unmap or attach/detach)

By unmap segments, do you mean [memfd.Unmap](https://pkg.go.dev/github.com/justincormack/go-memfd#Memfd.Unmap)

**Comment by edwarnicke** [comment]
> If we plan to make Attachment a global variable, not sure we'll want/need to track AppAttachReplyMsg in it.
Attachment is a global *type* but not a global *variable*

**Comment by florincoras** [comment]
> > We'll also need to unmap segments. No preference for naming but we should choose a pair of prefixes and use it consistently (e.g., new/free or map/unmap or attach/detach)
> 
> By unmap segments, do you mean [memfd.Unmap](https://pkg.go.dev/github.com/justincormack/go-memfd#Memfd.Unmap)

Yup. VPP can ask the app/vcl to unmap segments, not the first one for a worker though, if it goes empty

**Comment by florincoras** [comment]
> > If we plan to make Attachment a global variable, not sure we'll want/need to track AppAttachReplyMsg in it.
Attachment is a global _type_ but not a global _variable_

We might want a global variable as well, that tracks app level state as opposed to worker level state. Although, if we plan to support only multi-thread (not multi-process like nginx) apps we might not need it. So probably we can ignore this for now.

**Comment by harshgondaliya** [comment]
@edwarnicke @florincoras I have submitted a PR having code for this issue.
