### ISSUE TITLE
Attach to VPP Hoststack using Go API

### ISSUE THREAD

**Issue by edwarnicke** [godirect/hoststack#2]
Use the [AppAttach](https://github.com/edwarnicke/govpp/blob/79125273957c1ff3c5006af1f6bff1081962fa7e/binapi/session/session_rpc.ba.go#L46) go API call to attach to VPP for hoststack.

Documentation for the meaning of the fields is here: https://github.com/FDio/vpp/blob/master/src/vnet/session/session.api#L31

Do this after #1

**Comment by edwarnicke** [comment]
@florincoras - FYI

**Comment by florincoras** [comment]
The above should be enough, but a bit more context based on VCL C code, to help clarify the expected order of operations:

1. Send attach [message](https://github.com/FDio/vpp/blob/master/src/vnet/session/session.api#L37), e.g., https://github.com/FDio/vpp/blob/master/src/vcl/vcl_bapi.c#L646
2. Handle attach reply [message](https://github.com/FDio/vpp/blob/master/src/vnet/session/session.api#L59), e.g., https://github.com/FDio/vpp/blob/master/src/vcl/vcl_bapi.c#L67
3. To detach, either use [message](https://github.com/FDio/vpp/blob/master/src/vnet/session/session.api#L77), e.g., https://github.com/FDio/vpp/blob/master/src/vcl/vcl_bapi.c#L359 or delete the app worker using https://github.com/FDio/vpp/blob/master/src/vcl/vcl_bapi.c#L682 and [message](https://github.com/FDio/vpp/blob/master/src/vnet/session/session.api#L160). 

You can find govpp equivalents for all messages [here](https://github.com/edwarnicke/govpp/blob/79125273957c1ff3c5006af1f6bff1081962fa7e/binapi/session/session.ba.go)

**Comment by harshgondaliya** [comment]
@edwarnicke Just submitted a PR showing my work for this exercise.

**Comment by edwarnicke** [comment]
Closed by https://github.com/godirect/hoststack/pull/3
