### ISSUE TITLE
Binary marshalling/unmarshalling of AppAttach message

### ISSUE THREAD

**Issue by edwarnicke** [godirect/hoststack#6]
After #5 you will need to be able to marshal the [app_sapi_attach_msg_](https://github.com/FDio/vpp/blob/9f562cd9e651df8579ea05f5f3b77b8b912938c2/src/vnet/session/application_interface.h#L822-L826) and unmarshall the [app_sapi_attach_reply_msg_](https://github.com/FDio/vpp/blob/9f562cd9e651df8579ea05f5f3b77b8b912938c2/src/vnet/session/application_interface.h#L832-L843).  These are binary messages, the binary layout of which is described by the linked C source code.

My suggestion would be that you look at writing analogous Go structs for these messages, and implementing the 
[BinaryMarshaller](https://golang.org/pkg/encoding/#BinaryMarshaler) and [BinaryUnMarshaller](https://golang.org/pkg/encoding/#BinaryUnmarshaler) for them.  

You are likely to find [encoding/binary](https://golang.org/pkg/encoding/binary/) useful in this pursuit.

[This article](https://www.gobeyond.dev/encoding/) may be helpful.

In particular you will want to use [binary.BigEndian](https://golang.org/pkg/encoding/binary/#pkg-variables) (ie, Network Byte Order) to write to a []byte array.

[This article](https://medium.com/learning-the-go-programming-language/encoding-data-with-the-go-binary-package-42c7c0eb3e73) is likely to also be helpful.

**Comment by edwarnicke** [comment]
Once you have written the message structs and their BinaryMarshaller/UnMarshaller I suggest you write [Go Tests](https://gobyexample.com/testing) (more info [here](https://golang.org/pkg/testing/) and [here](https://www.pullrequest.com/blog/unit-testing-in-go/)

**Comment by harshgondaliya** [comment]
@edwarnicke I have resolved all the CI issues and submitted a PR for #5 and #6 exercises
